<?php

namespace AppBundle\Repository;

/**
 * MusicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicRepository extends \Doctrine\ORM\EntityRepository
{
}
