<?php

namespace AppBundle\Repository;

/**
 * PlaylistMusicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistMusicRepository extends \Doctrine\ORM\EntityRepository
{
}
